# fly.toml app configuration file generated for publish-fragrant-cloud-3528 on 2025-01-31T10:45:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'publish-fragrant-cloud-3528'
primary_region = 'arn'

[build]
builtin = "python"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true  # Allows stopping when inactive but doesn't delete the machine
auto_start_machines = true  # Ensures the machine starts when a request comes in
min_machines_running = 1  # Always keeps at least 1 machine running
processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "ccraft_data"
  destination = "/data"